const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'index.html');
let content = fs.readFileSync(filePath, 'utf8');

console.log('Phase 3: Move WoW Comparison to Weekly Budgeting page...');

// Find and remove WoW Comparison section from dashboard (if it exists there)
const wowSectionPattern = /<!-- WoW Comparison -->[\s\S]*?<\/section>\s*<!-- Trend Analysis/;
const wowMatch = content.match(wowSectionPattern);

if (wowMatch) {
    console.log('Found WoW section, will relocate it');
    content = content.replace(wowMatch[0], '<!-- Trend Analysis');
}

// Add WoW Comparison to Weekly Budgeting page (after topbar/filters, before kpi-grid)
const weeklyBudgetingFiltersEnd = content.indexOf('<section class="kpi-grid">', content.indexOf('id="weekly-budgeting-page"'));

if (weeklyBudgetingFiltersEnd !== -1) {
    const wowHTML = `
        <!-- WoW Comparison -->
        <section class="card panel">
          <div class="panel-header">
            <h2>Week-over-Week Comparison</h2>
            <span class="panel-note">Perbandingan performa minggu ini vs minggu sebelumnya (independent dari target)</span>
          </div>
          <div class="wow-grid" id="wowComparisonGrid" style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; padding: 16px;">
            <!-- Content generated by JavaScript -->
          </div>
        </section>

        `;
    
    content = content.slice(0, weeklyBudgetingFiltersEnd) + wowHTML + content.slice(weeklyBudgetingFiltersEnd);
    console.log('Added WoW Comparison to Weekly Budgeting page');
}

// Update renderWoWComparison to be independent (recalculate fresh each time, not using target data)
const oldRenderWoW = `function renderWoWComparison() {
        const grid = document.getElementById('wowComparisonGrid');
        if (!grid) return;

        const [start, end] = getSelectedWeekRange();
        const [prevStart, prevEnd] = [new Date(start.getTime() - 7 * 24 * 60 * 60 * 1000), new Date(end.getTime() - 7 * 24 * 60 * 60 * 1000)];

        const currentWeekRows = weeklyRowsInRange(start, end).detailRows;
        const prevWeekRows = weeklyRowsInRange(prevStart, prevEnd).detailRows;`;

const newRenderWoW = `function renderWoWComparison() {
        const grid = document.getElementById('wowComparisonGrid');
        if (!grid) return;

        const [start, end] = getSelectedWeekRange();
        const [prevStart, prevEnd] = [new Date(start.getTime() - 7 * 24 * 60 * 60 * 1000), new Date(end.getTime() - 7 * 24 * 60 * 60 * 1000)];

        // Independent calculation - directly from actual data, not affected by target/budgeting
        const currentWeekRows = weeklyRowsInRange(start, end).detailRows;
        const prevWeekRows = weeklyRowsInRange(prevStart, prevEnd).detailRows;`;

content = content.replace(oldRenderWoW, newRenderWoW);
console.log('Updated renderWoWComparison to be independent');

fs.writeFileSync(filePath, content, 'utf8');
console.log('Phase 3 complete!');
