const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'index.html');
let content = fs.readFileSync(filePath, 'utf8');

console.log('File size:', content.length, 'chars');

// 1. Add Chart.js CDN in <head>
const chartJsCDN = '\n  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>';
const sheetJsCDN = '\n  <script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js"></script>';

// Insert after last style tag and before </head>
if (!content.includes('cdn.jsdelivr.net/npm/chart.js')) {
    content = content.replace('</style>', \</style>\\\);
    console.log('Added Chart.js and SheetJS CDN');
}

// 2. Add Bulk Import UI after budget proposal buttons
const bulkImportUI = \
            <div class="row-actions" style="margin-top: 16px; padding-top: 16px; border-top: 1px solid #eee;">
              <button class="panel-action" id="bulkImportToggle">Import CSV/Excel</button>
              <input type="file" id="bulkImportFile" accept=".csv,.txt,.xlsx,.xls" style="display: none;">
              <button class="panel-action" id="exportBudgetProposal">Export ke Excel</button>
              <button class="panel-action primary" id="saveRecommendationBtn">Save Rekomendasi</button>
            </div>
            <div id="bulkImportArea" style="display: none; margin-top: 16px; background: #f8f9fa; padding: 16px; border-radius: 8px;">
              <textarea id="bulkImportTextarea" placeholder="Paste CSV data (kolom: advertiser, platform, product, manualBudget, manualTargetCac)&#10;Contoh: Adv1,Shopee,ProductA,1000000,25" style="width: 100%; height: 120px; font-family: monospace; font-size: 14px; padding: 12px; border: 1px solid #ddd; border-radius: 6px;"></textarea>
              <div style="margin-top: 12px; display: flex; gap: 8px;">
                <button class="panel-action" id="parseBulkCSV">Parse & Tambah</button>
                <button class="row-action" id="cancelBulkImport">Cancel</button>
              </div>
              <div id="bulkImportPreview" style="margin-top: 16px; font-size: 13px; color: #666;"></div>
            </div>
\;

if (!content.includes('id="bulkImportToggle"')) {
    content = content.replace(
        '<button class="row-action" id="resetBudgetProposalRows" type="button">Reset Rekomendasi</button>',
        \<button class="row-action" id="resetBudgetProposalRows" type="button">Reset Rekomendasi</button>
\\
    );
    console.log('Added Bulk Import UI');
}

// 3. Add Auto-save indicator near target cards
const autoSaveIndicator = \
          <div style="display: flex; justify-content: flex-end; align-items: center; gap: 8px; margin-top: 8px; font-size: 13px;">
            <div id="autoSaveStatus" style="color: #666;">Auto-save aktif (10 detik)</div>
            <div id="lastSaveTime" style="color: #888;">Terakhir: -</div>
          </div>
\;

if (!content.includes('id="autoSaveStatus"')) {
    content = content.replace(
        '<small>dari target <span id="weeklyTargetDisplay">Rp0</span></small>',
        \<small>dari target <span id="weeklyTargetDisplay">Rp0</span></small>
\\
    );
    console.log('Added auto-save indicator');
}

// 4. Add WoW Comparison section before Last Week table
const wowComparisonSection = \
        <!-- WoW Comparison -->
        <section class="card panel">
          <div class="panel-header">
            <h2>Week-over-Week Comparison</h2>
            <span class="panel-note">Perbandingan performa minggu ini vs minggu sebelumnya</span>
          </div>
          <div class="wow-grid" id="wowComparisonGrid" style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; padding: 16px;">
            <!-- Content generated by JavaScript -->
          </div>
        </section>
\;

if (!content.includes('Week-over-Week Comparison')) {
    content = content.replace(
        '<section class="card panel">',
        \\
<section class="card panel">\
    );
    console.log('Added WoW Comparison section');
}

// 5. Add Chart section after WoW Comparison
const chartSection = \
        <!-- Trend Analysis Chart -->
        <section class="card panel">
          <div class="panel-header">
            <h2>Trend Analysis (4 Minggu Terakhir)</h2>
            <span class="panel-note">Tren budget, revenue, dan performa mingguan</span>
          </div>
          <div style="padding: 16px;">
            <canvas id="trendChart" style="width: 100%; height: 300px;"></canvas>
          </div>
          <div style="display: flex; gap: 8px; padding: 16px; border-top: 1px solid #eee;">
            <button class="panel-action" id="updateTrendChart">Update Chart</button>
            <button class="panel-action" id="exportChartData">Export Data Chart</button>
          </div>
        </section>
\;

if (!content.includes('Trend Analysis')) {
    // Insert after WoW Comparison section (which we just added)
    content = content.replace(
        'Week-over-Week Comparison</h2>',
        \Week-over-Week Comparison</h2>\
    );
    // Let's do simpler: insert before </section> of WoW section
    const wowSectionEnd = '</div>\n        </section>';
    const replacement = \</div>\n        </section>\n\\;
    content = content.replace(wowSectionEnd, replacement);
    console.log('Added Chart section');
}

// 6. Add Revenue Distribution Warning UI
const revenueWarningUI = \
          <!-- Revenue Distribution Warning -->
          <div id="revenueDistributionWarning" style="display: none; margin: 16px 0; padding: 12px; background: #fef2f2; border: 1px solid #fecaca; border-radius: 8px;">
            <div style="display: flex; align-items: center; gap: 8px;">
              <span style="color: #dc2626; font-weight: bold;">⚠️ Warning:</span>
              <span id="warningMessage"></span>
            </div>
          </div>
\;

if (!content.includes('id="revenueDistributionWarning"')) {
    // Add after the budget proposal table
    content = content.replace(
        '<div class="pam-summary" id="budgetProposalPamBody"></div>',
        \<div class="pam-summary" id="budgetProposalPamBody"></div>
\\
    );
    console.log('Added Revenue Warning UI');
}

// 7. Add Auto-save interval logic at end of script (before init())
const autoSaveFunctions = \
    // ========== AUTO-SAVE & FEATURES ==========
    const AUTO_SAVE_INTERVAL = 10000; // 10 seconds
    const BUDGETING_STORAGE_KEY = 'ngkr_budgeting_proposal';
    let autoSaveTimer = null;

    function setupAutoSave() {
        // Load saved proposal rows
        const saved = localStorage.getItem(BUDGETING_STORAGE_KEY);
        if (saved) {
            try {
                const parsed = JSON.parse(saved);
                if (Array.isArray(parsed) && parsed.length > 0) {
                    weeklyProposalRows = parsed;
                    console.log('Loaded', parsed.length, 'saved proposal rows');
                }
            } catch (e) {
                console.warn('Failed to load saved proposals:', e);
            }
        }

        // Setup auto-save interval
        autoSaveTimer = setInterval(() => {
            saveBudgetingData();
        }, AUTO_SAVE_INTERVAL);

        // Update last save time display
        updateLastSaveTime();
    }

    function saveBudgetingData() {
        try {
            localStorage.setItem(BUDGETING_STORAGE_KEY, JSON.stringify(weeklyProposalRows));
            updateLastSaveTime();
            console.log('Auto-saved', weeklyProposalRows.length, 'proposal rows');
            return true;
        } catch (e) {
            console.warn('Auto-save failed:', e);
            return false;
        }
    }

    function updateLastSaveTime() {
        const els = window.els || {};
        if (els.lastSaveTime) {
            const now = new Date();
            const timeStr = now.toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit', second: '2-digit' });
            els.lastSaveTime.textContent = \Terakhir: \\;
        }
    }

    // Bulk Import Functions
    function setupBulkImport() {
        const els = window.els || {};
        if (!els.bulkImportToggle) return;

        els.bulkImportToggle.addEventListener('click', () => {
            const area = els.bulkImportArea;
            area.style.display = area.style.display === 'none' ? 'block' : 'none';
            if (area.style.display === 'block') {
                els.bulkImportTextarea.focus();
            }
        });

        els.cancelBulkImport.addEventListener('click', () => {
            els.bulkImportArea.style.display = 'none';
            els.bulkImportTextarea.value = '';
            els.bulkImportPreview.innerHTML = '';
        });

        els.parseBulkCSV.addEventListener('click', parseBulkCSVData);
        els.bulkImportFile.addEventListener('change', handleFileImport);
    }

    function parseBulkCSVData() {
        const els = window.els || {};
        const text = els.bulkImportTextarea.value.trim();
        if (!text) {
            alert('Masukkan data CSV terlebih dahulu');
            return;
        }

        const lines = text.split('\n').filter(line => line.trim());
        const rows = [];
        let successCount = 0;
        let errorCount = 0;

        lines.forEach((line, index) => {
            const columns = line.split(',').map(col => col.trim());
            if (columns.length >= 5) {
                const [advertiser, platform, product, manualBudget, manualTargetCac] = columns;
                rows.push({
                    id: \ulk-\-\\,
                    advertiser: advertiser,
                    platform: platform,
                    product: product,
                    mode: 'manual',
                    manualBudget: manualBudget,
                    manualTargetCac: parseFloat(manualTargetCac) || 0,
                    adminRate: platform.toLowerCase().includes('shopee') ? 18 : 
                              platform.toLowerCase().includes('tiktok') ? 16 : 0
                });
                successCount++;
            } else {
                errorCount++;
            }
        });

        // Add to existing proposal rows
        weeklyProposalRows = weeklyProposalRows.concat(rows);
        
        // Update preview
        els.bulkImportPreview.innerHTML = \
            <strong>\ baris berhasil diimpor, \ error</strong><br>
            <small>Total proposal rows sekarang: \</small>
        \;

        // Render updates
        if (typeof renderWeeklyBudgetingPage === 'function') {
            renderWeeklyBudgetingPage();
        }

        // Auto-save after import
        saveBudgetingData();
    }

    function handleFileImport(event) {
        const file = event.target.files[0];
        if (!file) return;

        const reader = new FileReader();
        reader.onload = function(e) {
            els.bulkImportTextarea.value = e.target.result;
            parseBulkCSVData();
        };
        reader.readAsText(file);
    }

    // Export to Excel
    function setupExportFunctions() {
        const els = window.els || {};
        if (!els.exportBudgetProposal) return;

        els.exportBudgetProposal.addEventListener('click', exportBudgetProposalToExcel);
        els.exportChartData.addEventListener('click', exportChartDataToExcel);
    }

    function exportBudgetProposalToExcel() {
        const rows = weeklyProposalRows.map(row => ({
            Advertiser: row.advertiser || '',
            Platform: row.platform || '',
            Product: row.product || '',
            Mode: row.mode || '',
            Budget: row.mode === 'manual' ? row.manualBudget : row.recommendationBudget || 0,
            TargetCAC: row.mode === 'manual' ? row.manualTargetCac : row.recommendationTargetCac || 0,
            AdminRate: row.adminRate || 0
        }));

        // Create CSV
        const headers = Object.keys(rows[0] || {});
        const csvRows = [headers.join(',')];
        rows.forEach(row => {
            const values = headers.map(header => \"\"\);
            csvRows.push(values.join(','));
        });

        const csvContent = csvRows.join('\n');
        const blob = new Blob([csvContent], { type: 'text/csv' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = \udget-proposal-\.csv\;
        a.click();
        URL.revokeObjectURL(url);
    }

    // Save Recommendation Flow
    function setupSaveRecommendation() {
        const els = window.els || {};
        if (!els.saveRecommendationBtn) return;

        els.saveRecommendationBtn.addEventListener('click', () => {
            if (!weeklyProposalRows.length) {
                alert('Belum ada rekomendasi untuk disimpan');
                return;
            }

            if (confirm(\Simpan \ baris rekomendasi budgeting?\\n\\nData akan tersimpan dan dapat dilihat oleh semua user.\)) {
                // Save to server or localStorage with confirmation
                const saved = saveBudgetingData();
                if (saved) {
                    alert('Rekomendasi berhasil disimpan!');
                    // Trigger data sync to other users (simulated)
                    if (typeof broadcastSave === 'function') {
                        broadcastSave();
                    }
                }
            }
        });
    }

    // Initialize all new features
    function setupNewFeatures() {
        setupAutoSave();
        setupBulkImport();
        setupExportFunctions();
        setupSaveRecommendation();
        
        // Add to window.els
        const newElements = {
            bulkImportToggle: document.getElementById('bulkImportToggle'),
            bulkImportArea: document.getElementById('bulkImportArea'),
            bulkImportTextarea: document.getElementById('bulkImportTextarea'),
            bulkImportFile: document.getElementById('bulkImportFile'),
            bulkImportPreview: document.getElementById('bulkImportPreview'),
            parseBulkCSV: document.getElementById('parseBulkCSV'),
            cancelBulkImport: document.getElementById('cancelBulkImport'),
            exportBudgetProposal: document.getElementById('exportBudgetProposal'),
            saveRecommendationBtn: document.getElementById('saveRecommendationBtn'),
            autoSaveStatus: document.getElementById('autoSaveStatus'),
            lastSaveTime: document.getElementById('lastSaveTime'),
            wowComparisonGrid: document.getElementById('wowComparisonGrid'),
            trendChart: document.getElementById('trendChart'),
            updateTrendChart: document.getElementById('updateTrendChart'),
            exportChartData: document.getElementById('exportChartData'),
            revenueDistributionWarning: document.getElementById('revenueDistributionWarning'),
            warningMessage: document.getElementById('warningMessage')
        };

        // Merge with existing els
        if (window.els) {
            Object.assign(window.els, newElements);
        }

        console.log('New features initialized');
    }

    // Call setupNewFeatures after init
    const originalInit = window.init;
    window.init = function() {
        if (typeof originalInit === 'function') {
            originalInit();
        }
        setTimeout(setupNewFeatures, 500); // Wait a bit for DOM to be ready
    };
\;

// Insert before init() call
if (!content.includes('const AUTO_SAVE_INTERVAL')) {
    // Find the init(); call before </script>
    const initCallPos = content.lastIndexOf('init();');
    if (initCallPos !== -1) {
        content = content.slice(0, initCallPos) + autoSaveFunctions + '\n\n    ' + content.slice(initCallPos);
        console.log('Added auto-save and feature functions');
    }
}

// Save the modified file
fs.writeFileSync(filePath, content, 'utf8');
console.log('File updated successfully!');
