const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'index.html');
let content = fs.readFileSync(filePath, 'utf8');

console.log('File size:', content.length, 'chars');

// 1. Add Chart.js and SheetJS CDNs
const cdn_script = "\n  <script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\n  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js\"></script>";
if (!content.includes("cdn.jsdelivr.net/npm/chart.js")) {
    content = content.replace("</style>", "</style>" + cdn_script);
    console.log("Added CDN scripts");
}

// 2. Add Bulk Import UI
const bulk_import_ui = `
            <div class="row-actions" style="margin-top: 16px; padding-top: 16px; border-top: 1px solid #eee; display: flex; gap: 8px; flex-wrap: wrap;">
              <button class="panel-action" id="bulkImportToggle" type="button">Import CSV/Excel</button>
              <input type="file" id="bulkImportFile" accept=".csv,.txt,.xlsx,.xls" style="display: none;">
              <button class="panel-action" id="exportBudgetProposal" type="button">Export ke Excel</button>
              <button class="panel-action primary" id="saveRecommendationBtn" type="button">Save Rekomendasi</button>
            </div>
            <div id="bulkImportArea" style="display: none; margin-top: 16px; background: #f8f9fa; padding: 16px; border-radius: 8px;">
              <textarea id="bulkImportTextarea" placeholder="Paste CSV/Excel data (format: advertiser, platform, product, manualBudget, manualTargetCac)\nContoh: Adv1,Shopee,ProductA,1000000,25" style="width: 100%; height: 120px; font-family: monospace; font-size: 14px; padding: 12px; border: 1px solid #ddd; border-radius: 6px;"></textarea>
              <div style="margin-top: 12px; display: flex; gap: 8px;">
                <button class="panel-action" id="parseBulkCSV" type="button">Parse & Tambah</button>
                <button class="row-action" id="cancelBulkImport" type="button">Cancel</button>
              </div>
              <div id="bulkImportPreview" style="margin-top: 16px; font-size: 13px; color: #666;"></div>
            </div>
`;
if (!content.includes('id="bulkImportToggle"')) {
    content = content.replace(
        '<button class="row-action" id="resetBudgetProposalRows" type="button">Reset Rekomendasi</button>',
        '<button class="row-action" id="resetBudgetProposalRows" type="button">Reset Rekomendasi</button>' + bulk_import_ui
    );
    console.log("Added Bulk Import UI");
}

// 3. Add Auto-save indicator
const auto_save_indicator = `
          <div style="display: flex; justify-content: flex-end; align-items: center; gap: 8px; margin-top: 8px; font-size: 13px;">
            <div id="autoSaveStatus" style="color: #666;">Auto-save aktif (10 detik)</div>
            <div id="lastSaveTime" style="color: #888;">Terakhir: -</div>
          </div>
`;
if (!content.includes('id="autoSaveStatus"')) {
    content = content.replace(
        '<small>dari target <span id="weeklyTargetDisplay">Rp0</span></small>',
        '<small>dari target <span id="weeklyTargetDisplay">Rp0</span></small>' + auto_save_indicator
    );
    console.log("Added auto-save indicator");
}

// 4. Add WoW Comparison section
const wow_section = `
        <!-- WoW Comparison -->
        <section class="card panel">
          <div class="panel-header">
            <h2>Week-over-Week Comparison</h2>
            <span class="panel-note">Perbandingan performa minggu ini vs minggu sebelumnya</span>
          </div>
          <div class="wow-grid" id="wowComparisonGrid" style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; padding: 16px;">
            <!-- Content generated by JavaScript -->
          </div>
        </section>
`;
if (!content.includes("Week-over-Week Comparison")) {
    content = content.replace(
        '<section class="card panel">',
        wow_section + "\n<section class=\"card panel\">"
    );
    console.log("Added WoW Comparison Section");
}

// 5. Add Chart section
const chart_section = `
        <!-- Trend Analysis Chart -->
        <section class="card panel">
          <div class="panel-header">
            <h2>Trend Analysis (4 Minggu Terakhir)</h2>
            <span class="panel-note">Tren budget, revenue, dan performa mingguan</span>
          </div>
          <div style="padding: 16px;">
            <canvas id="trendChart" style="width: 100%; height: 300px;"></canvas>
          </div>
          <div style="display: flex; gap: 8px; padding: 16px; border-top: 1px solid #eee;">
            <button class="panel-action" id="updateTrendChart" type="button">Update Chart</button>
            <button class="panel-action" id="exportChartData" type="button">Export Data Chart</button>
          </div>
        </section>
`;
if (!content.includes("Trend Analysis (4 Minggu Terakhir)")) {
    content = content.replace(
        wow_section,
        wow_section + "\n" + chart_section
    );
    console.log("Added Trend Chart Section");
}

// 6. Add Revenue Distribution Warning UI
const revenue_warning_ui = `
          <!-- Revenue Distribution Warning -->
          <div id="revenueDistributionWarning" style="display: none; margin: 16px 0; padding: 12px; background: #fef2f2; border: 1px solid #fecaca; border-radius: 8px;">
            <div style="display: flex; align-items: center; gap: 8px;">
              <span style="color: #dc2626; font-weight: bold;">⚠️ Warning:</span>
              <span id="warningMessage" style="color: #991b1b; font-weight: 500;"></span>
            </div>
          </div>
`;
if (!content.includes('id="revenueDistributionWarning"')) {
    content = content.replace(
        '<div class="pam-summary" id="budgetProposalPamBody"></div>',
        '<div class="pam-summary" id="budgetProposalPamBody"></div>\n' + revenue_warning_ui
    );
    console.log("Added Revenue Distribution Warning UI");
}

fs.writeFileSync(filePath, content, 'utf8');
console.log("HTML structure modifications done successfully!");
